/*
 * generated by Xtext 2.17.0
 */
package hu.bme.mit.gamma.logical.logicFunction.language.parser.antlr;

import com.google.inject.Inject;
import hu.bme.mit.gamma.logical.logicFunction.language.parser.antlr.internal.InternalLogicFunctionLanguageParser;
import hu.bme.mit.gamma.logical.logicFunction.language.services.LogicFunctionLanguageGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class LogicFunctionLanguageParser extends AbstractAntlrParser {

	@Inject
	private LogicFunctionLanguageGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLogicFunctionLanguageParser createParser(XtextTokenStream stream) {
		return new InternalLogicFunctionLanguageParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "LogicFunctionDiagram";
	}

	public LogicFunctionLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LogicFunctionLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
