/*
 * generated by Xtext 2.17.0
 */
package hu.bme.mit.gamma.logical.logicFunction.language


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class LogicFunctionLanguageStandaloneSetup extends LogicFunctionLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new LogicFunctionLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
