/*
 * generated by Xtext 2.17.0
 */
package hu.bme.mit.gamma.logical.logicBase.language


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class LogicBaseLanguageStandaloneSetup extends LogicBaseLanguageStandaloneSetupGenerated {

	def static void doSetup() {
		new LogicBaseLanguageStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
