/*
 * generated by Xtext 2.17.0
 */
package hu.bme.mit.gamma.logical.logicBase.language


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class LogicBaseLanguageRuntimeModule extends AbstractLogicBaseLanguageRuntimeModule {
}
