/**
 * generated by Xtext 2.17.0
 */
package hu.bme.mit.gamma.logical.logicBase.language.ide;

import hu.bme.mit.gamma.logical.logicBase.language.ide.AbstractLogicBaseLanguageIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class LogicBaseLanguageIdeModule extends AbstractLogicBaseLanguageIdeModule {
}
