/**
 * generated by Xtext 2.17.0
 */
package hu.bme.mit.gamma.logical.logicFunction.language.ui.quickfix;

import hu.bme.mit.gamma.logical.logicBase.language.ui.quickfix.LogicBaseLanguageQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class LogicFunctionLanguageQuickfixProvider extends LogicBaseLanguageQuickfixProvider {
}
