/*
 * generated by Xtext 2.17.0
 */
package hu.bme.mit.gamma.logical.logicFunction.language.scoping;

import hu.bme.mit.gamma.logical.logicBase.language.scoping.LogicBaseLanguageScopeProvider;

public abstract class AbstractLogicFunctionLanguageScopeProvider extends LogicBaseLanguageScopeProvider {
}
