/**
 * generated by Xtext 2.17.0
 */
package hu.bme.mit.gamma.logical.logicFunction.language;

import hu.bme.mit.gamma.logical.logicFunction.language.LogicFunctionLanguageStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class LogicFunctionLanguageStandaloneSetup extends LogicFunctionLanguageStandaloneSetupGenerated {
  public static void doSetup() {
    new LogicFunctionLanguageStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
