/**
 * generated by Xtext 2.17.0
 */
package hu.bme.mit.gamma.logical.logicFunction.language;

import hu.bme.mit.gamma.logical.logicFunction.language.AbstractLogicFunctionLanguageRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class LogicFunctionLanguageRuntimeModule extends AbstractLogicFunctionLanguageRuntimeModule {
}
