/*
 * generated by Xtext 2.17.0
 */
package hu.bme.mit.gamma.logical.logicFunction.language.ide


/**
 * Use this class to register ide components.
 */
class LogicFunctionLanguageIdeModule extends AbstractLogicFunctionLanguageIdeModule {
}
