/*
 * generated by Xtext 2.17.0
 */
package hu.bme.mit.gamma.logical.logicFunction.language.ui;

import com.google.inject.Injector;
import hu.bme.mit.gamma.logical.logicFunction.language.ui.internal.LanguageActivator;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LogicFunctionLanguageExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(LanguageActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		LanguageActivator activator = LanguageActivator.getInstance();
		return activator != null ? activator.getInjector(LanguageActivator.HU_BME_MIT_GAMMA_LOGICAL_LOGICFUNCTION_LANGUAGE_LOGICFUNCTIONLANGUAGE) : null;
	}

}
