/**
 * generated by Xtext 2.17.0
 */
package hu.bme.mit.gamma.logical.logicFunction.language.ui;

import hu.bme.mit.gamma.logical.logicFunction.language.ui.AbstractLogicFunctionLanguageUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class LogicFunctionLanguageUiModule extends AbstractLogicFunctionLanguageUiModule {
  public LogicFunctionLanguageUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
