/*
 * generated by Xtext 2.17.0
 */
package hu.bme.mit.gamma.logical.logicBase.language.parser.antlr;

import com.google.inject.Inject;
import hu.bme.mit.gamma.logical.logicBase.language.parser.antlr.internal.InternalLogicBaseLanguageParser;
import hu.bme.mit.gamma.logical.logicBase.language.services.LogicBaseLanguageGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class LogicBaseLanguageParser extends AbstractAntlrParser {

	@Inject
	private LogicBaseLanguageGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalLogicBaseLanguageParser createParser(XtextTokenStream stream) {
		return new InternalLogicBaseLanguageParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Interface";
	}

	public LogicBaseLanguageGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LogicBaseLanguageGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
