/**
 * generated by Xtext 2.17.0
 */
package hu.bme.mit.gamma.logical.logicFunction.language.ui.contentassist;

import hu.bme.mit.gamma.logical.logicFunction.language.ui.contentassist.AbstractLogicFunctionLanguageProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class LogicFunctionLanguageProposalProvider extends AbstractLogicFunctionLanguageProposalProvider {
}
