/*
 * generated by Xtext 2.17.0
 */
package hu.bme.mit.gamma.logical.logicBase.language.ide


/**
 * Use this class to register ide components.
 */
class LogicBaseLanguageIdeModule extends AbstractLogicBaseLanguageIdeModule {
}
