/*
 * generated by Xtext 2.17.0
 */
package hu.bme.mit.gamma.logical.logicFunction.language.validation;

import hu.bme.mit.gamma.logical.logicBase.language.validation.LogicBaseLanguageValidator;
import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public abstract class AbstractLogicFunctionLanguageValidator extends LogicBaseLanguageValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>(super.getEPackages());
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.mit.bme.hu/gamma/logical/logicFunction/Model"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("http://www.mit.bme.hu/gamma/logical/logicBase/Model"));
		return result;
	}
}
