/**
 * generated by Xtext 2.17.0
 */
package hu.bme.mit.gamma.logical.logicFunction.language.ide;

import hu.bme.mit.gamma.logical.logicFunction.language.ide.AbstractLogicFunctionLanguageIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class LogicFunctionLanguageIdeModule extends AbstractLogicFunctionLanguageIdeModule {
}
