/**
 * generated by Xtext 2.17.0
 */
package hu.bme.mit.gamma.logical.logicFunction.language.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import hu.bme.mit.gamma.logical.logicFunction.language.LogicFunctionLanguageRuntimeModule;
import hu.bme.mit.gamma.logical.logicFunction.language.LogicFunctionLanguageStandaloneSetup;
import hu.bme.mit.gamma.logical.logicFunction.language.ide.LogicFunctionLanguageIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class LogicFunctionLanguageIdeSetup extends LogicFunctionLanguageStandaloneSetup {
  @Override
  public Injector createInjector() {
    LogicFunctionLanguageRuntimeModule _logicFunctionLanguageRuntimeModule = new LogicFunctionLanguageRuntimeModule();
    LogicFunctionLanguageIdeModule _logicFunctionLanguageIdeModule = new LogicFunctionLanguageIdeModule();
    return Guice.createInjector(Modules2.mixin(_logicFunctionLanguageRuntimeModule, _logicFunctionLanguageIdeModule));
  }
}
