/**
 * generated by Xtext 2.17.0
 */
package hu.bme.mit.gamma.logical.logicBase.language.ui;

import hu.bme.mit.gamma.logical.logicBase.language.ui.AbstractLogicBaseLanguageUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class LogicBaseLanguageUiModule extends AbstractLogicBaseLanguageUiModule {
  public LogicBaseLanguageUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
